import React from 'react'
import Head from 'next/head'
import Navbar from '../components/Navbar'

const index = () => {
  return (
    <div>
      <Head>
        <title>Landing Page Build</title>
        <meta name='Landing Page' content='Generated by create next app'/>
      </Head>
      <div>
        <Navbar />
      </div>
    </div>
  )
}

export default index