import React from 'react'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'

const index = () => {
  return (
    <div>
      <Head>
        <title>Landing Page Build</title>
        <meta name='Landing Page' content='Generated by create next app'/>
      </Head>
      {/* NavBar */}
      <Navbar />

      {/* Hero Section */}
      <Hero />
    </div>
  )
}

export default index